app/web/models/__init__.py
#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# author:muji
# datetime:2019/8/6 20:44
import time

from flask import current_app
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import desc

db = SQLAlchemy()


class Base(db.Model):
    __abstract__ = True

    id = db.Column(db.Integer, primary_key=True)
    # 数据的生成时间
    created_at = db.Column(db.Integer, default=int(time.time()))
    # 数据的修改
    updated_at = db.Column(db.Integer, default=int(time.time()), onupdate=int(time.time()))
    # status
    status = db.Column(db.SmallInteger, default=1)

    @classmethod
    def all(cls):
        return cls.query.order_by(desc(cls.updated_at)).all()

    @classmethod
    def paginate(cls, page):
        """分页器"""
        return cls.query.paginate(
            page=int(page), per_page=current_app.config['PER_PAGE'], error_out=False)


class User(Base):
    username = db.Column(db.String(32), nullable=False, default='', unique=True)


class ProjectInfo(Base):
    project_name = db.Column(db.String(32), nullable=False, default='', unique=True)
    simple_desc = db.Column(db.String(500), nullable=False, default='')

app/web/forms/__init__.py
#!/usr/bin/env python3
#-*- coding:utf-8 -*-
# author:muji
# datetime:2019/8/8 21:59
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired, Length


class ProjectAddForm(FlaskForm):
    # form_model = ProjectInfo
    project_name = StringField(label='项目名称', validators=[DataRequired(), Length(
        max=64, min=1)])
    simple_desc = TextAreaField(label='项目描述', validators=[Length(max=512, min=0)])

app/__init__.py
"""初始化 app 核心对象.

配置相关的一些插件。
"""

from flask import Flask
from flask_migrate import Migrate

from app.config import config
from app.web.models import db
from app.web.template_env import str_time

app = Flask(__name__)
migrate = Migrate()

# app.config = Config()
#
# 其他的初始化东西，数据库

def create_app():
    """初始化"""
    # 初始化数据库
    app.config.from_object(config)
    db.init_app(app)
    migrate.init_app(app, db)
    # 配置文件
    # 自定义的错误处理机制
    # 模板过滤器注册
    # app.add_template_filter

    # 注册蓝图
    from app.web import web
    app.register_blueprint(web)

    # 添加过滤器
    app.add_template_filter(str_time)

    return app

app/web/__init__.py
#!/usr/bin/env python3
#-*- coding:utf-8 -*-
# author:muji
# datetime:2019/8/6 20:16
#MVC 分层思想
# wtf 验证层。

from flask import Blueprint

web = Blueprint('web', __name__)

# 路由
from .views import index, cases, modules, projects, suites

# 大型应用 路由==> app

app/web/template_env/__init__.py
#!/usr/bin/env python3
#-*- coding:utf-8 -*-
# author:muji
# datetime:2019/8/8 21:19
from datetime import datetime

def str_time(ts):
    return datetime.fromtimestamp(ts)

app/web/views/cases.py
#!/usr/bin/env python3
#-*- coding:utf-8 -*-
# author:muji
# datetime:2019/8/6 21:27

from flask import render_template

from app.web import web


@web.route('/list_cases')
def list_cases():
    return 'projects'

@web.route('/create_case')
def create_case():
    return 'projects'

app/web/views/index.py
#!/usr/bin/env python3
#-*- coding:utf-8 -*-
# author:muji
# datetime:2019/8/6 20:23
from flask import render_template

from app.web import web
from app.web.models import ProjectInfo


@web.route('/')
def index():
    # 数据层逻辑
    # all()
    projects = ProjectInfo.query.all()
    return render_template('index.html', projects=projects)

app/web/views/modules.py
#!/usr/bin/env python3
#-*- coding:utf-8 -*-
# author:muji
# datetime:2019/8/6 21:27

from flask import render_template

from app.web import web


@web.route('/list_modules')
def list_modules():
    return 'projects'

@web.route('/create_module')
def create_module():
    return 'projects'

app/web/views/projects.py
#!/usr/bin/env python3
#-*- coding:utf-8 -*-
# author:muji
# datetime:2019/8/6 21:26

from flask import render_template, request

from app.web import web
from app.web.forms import ProjectAddForm
from app.web.models import ProjectInfo


@web.route('/list_projects')
def list_projects():
    # 自己生成假数据 faker
    page = request.args.get('page', 1)
    paginate = ProjectInfo.paginate(page)
    projects = paginate.items
    return render_template('projects.html', projects=projects, paginate=paginate)
# 分页
# 展示的不完全数据
# 注册过滤器，分离

@web.route('/create_project', methods=['GET', 'POST'])
def create_project():
    # 验证层
    form = ProjectAddForm()
    if request.method == 'GET':
        return render_template('project.html', form=form)
    return 'edit project'

@web.route('/edit_project/<int:p_id>')
def edit_project(p_id):
    return 'edit projects'

@web.route('/delete_project')
def delete_project():
    return 'delete projects'

# 编辑项目
# 不仅要展示，get, post
# 数据校验

# 删除项目
# 逻辑删除

app/web/views/suites.py
#!/usr/bin/env python3
#-*- coding:utf-8 -*-
# author:muji
# datetime:2019/8/1 17:21

from app.web import web


@web.route('/suites')
def suites():
    return 'suites'


@web.route('/get_suite/<int:s_id>')
def get_suite(s_id=None):
    return f'get project {s_id}'


@web.route('/edit_suite/<int:s_id>')
def edit_suite(s_id=None):
    return f'get project {s_id}'


@web.route('/create_suite')
def create_suite():
    return f'create project'


@web.route('/delete_suite/<int:s_id>')
def delete_suite(s_id=None):
    return f'delete project {s_id}'

app/templates/base.html
<!doctype html>
<html class="no-js" lang="zh-CN">
<head>
    {% block header %} {% endblock %}

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>lemon测试-{% block title %} {% endblock %}</title>
    <meta name="keywords" content="index">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=yes">
    <meta name="renderer" content="webkit">
    <meta http-equiv="Cache-Control" content="no-siteapp"/>
    <meta name="apple-mobile-web-app-title" content="lemonTester"/>
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" media="screen"/>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap-fileinput/4.4.8/css/fileinput.css"/>
    <script src="https://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap-fileinput/4.4.8/js/fileinput.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap-fileinput/4.4.8/js/fileinput.min.js"></script>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap-fileinput/4.4.8/css/fileinput.min.css"/>

    <link href="https://cdn.bootcss.com/amazeui/2.7.2/css/amazeui.css" rel="stylesheet">

    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/admin.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/common.css') }}">

    <script src="https://cdn.bootcss.com/amazeui/2.7.2/js/amazeui.min.js"></script>
    <script src="https://cdn.bootcss.com/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.6/ace.js" type="text/javascript"
            charset="utf-8"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.6/ext-language_tools.js" type="text/javascript"
            charset="utf-8"></script>
    <script src="//apps.bdimg.com/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>

    <script src="{{ url_for('static', filename='assets/js/app.js') }}"></script>
    <script src="{{ url_for('static', filename='assets/js/commons.js') }}"></script>


</head>
<body class="modal-open">

<!-- 弹框内容，操作是否成功 -->
<div class="am-modal am-modal-alert" tabindex="-1" id="my-alert">
    <div class="am-modal-dialog">
        <div class="am-modal-hd">柠檬提示</div>
        <div class="am-modal-bd" id="my-alert_print">
            Sorry，服务器可能开小差啦, 请重试!
        </div>
        <div class="am-modal-footer">
            <span class="am-modal-btn">确定</span>
        </div>
    </div>
</div>

<div class="am-cf admin-main">
    <div class="daohang">
        <div class="title">柠檬班测试平台</div>
        <ul>
            <li>
                <button type="button" class="am-btn am-btn-default am-radius am-btn-xs"
                        onclick="location.href='{{ url_for('web.index') }}'">返回首页</button>
            </li>
            <li>
                <button type="button" class="am-btn am-btn-default am-radius am-btn-xs"
                        onclick="location.href='{{ url_for('web.list_projects') }}'">项目列表
                </button>
            </li>
            <li>
                <button type="button" class="am-btn am-btn-default am-radius am-btn-xs"
                        onclick="location.href='{{ url_for('web.list_modules') }}'">接口列表
                </button>
            </li>
            <li>
                <button type="button" class="am-btn am-btn-default am-radius am-btn-xs"
                        onclick="location.href='{{ url_for('web.list_cases') }}'">用例列表
                </button>
            </li>

        </ul>

{#        <div class="top-user"> 欢迎您：musen &nbsp;&nbsp;#}
{#            <a href='/api/log_out/'>注 销</a>#}
{#        </div>#}

    </div>
    <div class="nav-navicon admin-main admin-sidebar">


        <div class="sideMenu">
            <h3 class="am-icon-folder"><em></em> <a href="#">项目管理</a></h3>
            <ul>
                <li><a href="{{ url_for('web.list_projects') }}">项 目 列 表</a></li>
                <li><a href="{{ url_for('web.create_project') }}">新 增 项 目</a></li>
            </ul>
            <h3 class="am-icon-th-list"><em></em> <a href="#"> 接口管理</a></h3>
            <ul>
                <li><a href="{{ url_for('web.list_modules') }}">接 口 列 表</a></li>
                <li><a href="{{ url_for('web.create_module') }}">新 增 接口</a></li>
            </ul>
            <h3 class="am-icon-bug"><em></em> <a href="#">用例管理</a></h3>
            <ul>
                <li><a href="{{ url_for('web.list_cases') }}">用 例 列 表</a></li>
                <li><a href="{{ url_for('web.create_case') }}">新 增 用 例</a></li>
            </ul>


            <h3 class="am-icon-soundcloud"><em></em> <a href="#">测试套件</a></h3>
            <ul>
                <li><a href="{{ url_for('web.suites') }}">测 试 套 件 管 理</a></li>
                <li><a href="{{ url_for('web.create_suite') }}">创 建 套 件</a></li>
            </ul>

        </div>
        <!-- sideMenu End -->
    </div>



    {% block content %}

    {% endblock %}

    <script type="text/javascript">
        jQuery(".sideMenu").slide({
            titCell: "h3", //鼠标触发对象
            targetCell: "ul", //与titCell一一对应，第n个titCell控制第n个targetCell的显示隐藏
            effect: "slideDown", //targetCell下拉效果
            delayTime: 300, //效果时间
            triggerTime: 150, //鼠标延迟触发时间（默认150）
            defaultPlay: true,//默认是否执行效果（默认true）
            returnDefault: false //鼠标从.sideMen移走后返回默认状态（默认false）
        });



    </script>
</div>

</body>
</html>

app/templates/cases.html
{% extends "base.html" %}
{% block title %}用例信息{% endblock %}

{% block content %}

    <div class="am-modal am-modal-confirm" tabindex="-1" id="my-invalid">
        <div class="am-modal-dialog">
            <div class="am-modal-hd">柠檬提醒</div>
            <div class="am-modal-bd">
                亲，此操作会强制删除该项目下所有接口和用例，请谨慎操作！！！
            </div>
            <div class="am-modal-footer">
                <span class="am-modal-btn" data-am-modal-cancel>取消</span>
                <span class="am-modal-btn" data-am-modal-confirm>确定</span>
            </div>
        </div>
    </div>

    <div class="am-modal am-modal-confirm" tabindex="-1" id="select_case">
        <div class="am-modal-dialog">
            <div class="am-modal-hd">柠檬提醒</div>
            <div class="am-modal-bd">
                确认执行测试用例吗？
            </div>
            <div class="am-modal-footer">
                <span class="am-modal-btn" data-am-modal-cancel>取消</span>
                <span class="am-modal-btn" data-am-modal-confirm>确定</span>
            </div>
        </div>
    </div>


    <div class="admin-biaogelist">
        <div class="listbiaoti am-cf">
            <ul class="am-icon-flag on"> 用例列表</ul>
            <dl class="am-icon-home" style="float: right;"> 当前位置： 项目管理 > <a href="#">用例展示</a></dl>
            <dl>
                <button type="button" class="am-btn am-btn-danger am-round am-btn-xs am-icon-plus"
                        onclick="location='{{ url_for('web.create_case') }}'">新增用例
                </button>

                <button type="button" class="am-btn am-btn-danger am-round am-btn-xs am-icon-bug"
                        onclick="run_test_batch('case')">运行
                </button>
            </dl>
        </div>

        <form class="am-form am-g" id="case_list" name="case_list" method="post" action="/api/run_batch_test/">
            <table width="100%" class="am-table am-table-bordered am-table-radius am-table-striped">
                <thead>
                <tr class="am-success">
                    <th class="table-check"><input type="checkbox" id="select_all"/></th>
                    <th class="table-title">序号</th>
                    <th class="table-type">用例名称</th>
                    <th class="table-type">所属接口</th>
                    <th class="table-type">所属项目</th>
                    <th class="table-type">包含用例</th>
                    <th class="table-title">请求数据</th>
                    <th class="table-date am-hide-sm-only">创建时间</th>
                    <th width="163px" class="table-set">操作</th>
                </tr>
                </thead>
                <tbody>

                {% for foo in cases %}
                    <tr>
                        <td><input type="checkbox" name="case_{{ foo.id }}" value="{{ foo.id }}"/></td>
                        <td>{{ loop.index }}</td>
                        <td><a href="{{ url_for('web.edit_case', c_id=foo.id) }}">{{ foo.name }}</a>
                        </td>
                        <td>{{ foo.module.module_name }}</td>
                        <td>{{ foo.module.project.project_name }}</td>
                        <td>{{ foo.include }}</td>
                        <td>{{ foo.request }}</td>
                        <td class="am-hide-sm-only">{{ foo.created_at | str_time }}</td>
                        <td>
                            <div class="am-btn-toolbar">
                                <div class="am-btn-group am-btn-group-xs">
                                    <button type="button"
                                            class="am-btn am-btn-default am-btn-xs am-text-secondary am-round"
                                            data-am-popover="{content: '运行', trigger: 'hover focus'}"
                                            onclick="run_test('{{ foo.id }}', 'case')">
                                        <span class="am-icon-bug"></span></button>
                                    <button type="button"
                                            class="am-btn am-btn-default am-btn-xs am-text-secondary am-round"
                                            data-am-popover="{content: '编辑', trigger: 'hover focus'}"
                                            onclick="location='{{ url_for('web.edit_case', c_id=foo.id) }}'"> <span
                                            class="am-icon-pencil-square-o"></span></button>
                                    <button type="button"
                                            class="am-btn am-btn-default am-btn-xs am-text-danger am-round"
                                            data-am-popover="{content: '删除', trigger: 'hover focus'}"
                                            onclick="invalid('{{ foo.id }}')"><span
{#                                            onclick="location='{{ url_for('web.delete_project', p_id=foo.id) }}'"><span#}
                                            class="am-icon-trash-o"></span></button>
                                </div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}


                </tbody>
            </table>

            <div class="am-btn-group am-btn-group-xs">
                <button type="button" class="am-btn am-btn-default" onclick="location='{{ url_for('web.create_case') }}'"><span
                        class="am-icon-plus"></span> 新增
                </button>
            </div>

            <ul class="am-pagination am-fr">
                {% if paginate.has_prev %}
                    <a href="{{ url_for('web.list_cases', page=paginate.prev_num) }}">&lt;上一页</a>
                {% else %}
                    &lt;上一页
                {% endif %}

                {{ paginate.page }}

                {% if paginate.has_next %}
                    <a href="{{ url_for('web.list_cases', page=paginate.next_num) }}">下一页&gt;</a>
                {% else %}
                    下一页&gt;
                {% endif %}
            </ul>

            <hr/>
        </form>
    </div>
    <script type="text/javascript">
        // 删除项目的 modal
        function run_test_batch(type) {
            let csrf = '{{ csrf_token() }}';
            run_test_batch_common(type, csrf);
        }

        function invalid(id) {
            var csrf_token = "{{ csrf_token() }}";
            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrf_token);
                    }
                }
            });

            $('#my-invalid').modal({
                relatedTarget: this,
                onConfirm : function () {
                    del_data_ajax(id, '{{ url_for("web.delete_case") }}')
                },
                onCancel : function() {

                }

            })
        };


        $('#mode').change(function () {
            if ($('#mode').val() === 'false') {
                $('#report_name').removeAttr("readonly");
            } else {
                $('#report_name').attr('readonly', 'readonly');
            }
        });



        $('#select_all').click(function () {
            var isChecked = $(this).prop("checked");
            $("input[name^='project']").prop("checked", isChecked);
        })
    </script>

{% endblock %}

app/templates/module.html
{% extends "base.html" %}
{% block title %}新增接口{% endblock %}


{% block content %}

    <div class=" admin-content">

        <div class="admin-biaogelist">
            <div class="listbiaoti am-cf">
                <ul class="am-icon-flag on"> 新增接口</ul>
                <dl class="am-icon-home" style="float: right;"> 当前位置： 接口管理 > <a href="#">新增接口</a></dl>
            </div>
            <div class="fbneirong">
                {% set msgs =  get_flashed_messages()%}
                {% if msgs %}
                    {{ msgs[0] }}
                {% endif %}
                <form class="form-horizontal" id="add_module" action="{{ url_for("web.create_module") }}" method="post">
                    {{ form.hidden_tag() }}
                    <div class="form-group  has-feedback">
                        {{ form.module_name.label(class="control-label col-md-1 text-primary") }}
                        <div class="col-md-5">
                            {{ form.module_name(class='form-control') }}
                        </div>
                    </div>
                    <div class="form-group  has-feedback">
                        {{ form.project_id.label(class="control-label col-md-1 text-primary") }}
                        <div class="col-md-5">
                            {{ form.project_id(class='form-control') }}
                        </div>
                    </div>
                    <div class="form-group  has-feedback">
                        {{ form.simple_desc.label(class="control-label col-md-1 text-primary") }}
                        <div class="col-md-5">
                            {{ form.simple_desc(class='form-control') }}
                        </div>
                    </div>
                    <input type="submit" class="am-btn am-btn-success am-radius">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/project.html
{% extends "base.html" %}
{% block title %}单个项目{% endblock %}


{% block content %}

    <div class=" admin-content">

        <div class="admin-biaogelist">
            <div class="listbiaoti am-cf">
                <ul class="am-icon-flag on"> 新增项目</ul>
                <dl class="am-icon-home" style="float: right;"> 当前位置： 项目管理 > <a href="#">新增项目</a></dl>
            </div>
            <div class="fbneirong">
{#                {% set msgs =  get_flashed_messages()%}#}
{#                {% if msgs %}#}
{#                    {{ msgs[0] }}#}
{#                {% endif %}#}
                <form class="form-horizontal" id="add_project" action="{{ url_for("web.create_project") }}" method="post">
                    {{ form.hidden_tag() }}
                    <div class="form-group  has-feedback">
                        {{ form.project_name.label(class="control-label col-md-1 text-primary") }}
                        <div class="col-md-5">
                            {{ form.project_name(class='form-control') }}
                        </div>
                        {% set errors = form.project_name.errors %}
                        {% if errors %}
                            {{ errors[0] }}
                        {% endif %}
                    </div>
                    <div class="form-group  has-feedback">
                        {{ form.simple_desc.label(class="control-label col-md-1 text-primary") }}
                        <div class="col-md-5">
                            {{ form.simple_desc(class='form-control') }}
                        </div>
                        {% set errors = form.simple_desc.errors %}
                        {% if errors %}
                            {{ errors[0] }}
                        {% endif %}
                    </div>
                    <input type="submit" class="am-btn am-btn-success am-radius">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/projects.html
{% extends "base.html" %}
{% block title %}项目信息{% endblock %}

{% block content %}

    <div class="am-modal am-modal-confirm" tabindex="-1" id="my-invalid">
        <div class="am-modal-dialog">
            <div class="am-modal-hd">柠檬提醒</div>
            <div class="am-modal-bd">
                亲，此操作会强制删除该项目下所有接口和用例，请谨慎操作！！！
            </div>
            <div class="am-modal-footer">
                <span class="am-modal-btn" data-am-modal-cancel>取消</span>
                <span class="am-modal-btn" data-am-modal-confirm>确定</span>
            </div>
        </div>
    </div>

    <div class="am-modal am-modal-confirm" tabindex="-1" id="select_case">
        <div class="am-modal-dialog">
            <div class="am-modal-hd">柠檬提醒</div>
            <div class="am-modal-bd">
                确认执行测试用例吗？
            </div>
            <div class="am-modal-footer">
                <span class="am-modal-btn" data-am-modal-cancel>取消</span>
                <span class="am-modal-btn" data-am-modal-confirm>确定</span>
            </div>
        </div>
    </div>

    <div class="admin-biaogelist">
        <div class="listbiaoti am-cf">
            <ul class="am-icon-flag on"> 项目列表</ul>
            <dl class="am-icon-home" style="float: right;"> 当前位置： 项目管理 > <a href="#">项目展示</a></dl>
            <dl>
                <button type="button" class="am-btn am-btn-danger am-round am-btn-xs am-icon-plus"
                        onclick="location='{{ url_for('web.create_project') }}'">新增项目
                </button>
                <button type="button" class="am-btn am-btn-danger am-round am-btn-xs am-icon-bug"
                        onclick="run_test_batch('project')">运行
                </button>
            </dl>
        </div>

        <form class="am-form am-g" id="case_list" name="case_list" method="post" action="/api/run_batch_test/">
            <table width="100%" class="am-table am-table-bordered am-table-radius am-table-striped">
                <thead>
                <tr class="am-success">
                    <th class="table-check"><input type="checkbox" id="select_all"/></th>
                    <th class="table-title">序号</th>
                    <th class="table-type">项目名称</th>
                    <th class="table-type">项目简介</th>
                    <th class="table-title">接口/用例 数据</th>
                    <th class="table-date am-hide-sm-only">创建时间</th>
                    <th width="163px" class="table-set">操作</th>
                </tr>
                </thead>
                <tbody>

                {% for foo in projects %}
                    <tr>
                        <td><input type="checkbox" name="project_{{ foo.id }}" value="{{ foo.id }}"/></td>
                        <td>{{ loop.index }}</td>
                        <td><a href="{{ url_for('web.edit_project', p_id=foo.id) }}">{{ foo.project_name }}</a>
                        </td>
                        <td>{{ foo.simple_desc[:20] }}...</td>
                        <td>1/3</td>
                        <td class="am-hide-sm-only">{{ foo.created_at | str_time }}</td>
                        <td>
                            <div class="am-btn-toolbar">
                                <div class="am-btn-group am-btn-group-xs">
                                    <button type="button"
                                            class="am-btn am-btn-default am-btn-xs am-text-secondary am-round"
                                            data-am-popover="{content: '运行', trigger: 'hover focus'}"
                                            onclick="run_test('{{ foo.id }}', 'project')">
                                        <span class="am-icon-bug"></span></button>
                                    <button type="button"
                                            class="am-btn am-btn-default am-btn-xs am-text-secondary am-round"
                                            data-am-popover="{content: '编辑', trigger: 'hover focus'}"
                                            onclick="location='{{ url_for('web.edit_project', p_id=foo.id) }}'"> <span
                                            class="am-icon-pencil-square-o"></span></button>
                                    <button type="button"
                                            class="am-btn am-btn-default am-btn-xs am-text-danger am-round"
                                            data-am-popover="{content: '删除', trigger: 'hover focus'}"
                                            onclick="invalid('{{ foo.id }}')"><span
{#                                            onclick="location='{{ url_for('web.delete_project', p_id=foo.id) }}'"><span#}
                                            class="am-icon-trash-o"></span></button>
                                </div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}


                </tbody>
            </table>

            <div class="am-btn-group am-btn-group-xs">
                <button type="button" class="am-btn am-btn-default" onclick="location='{{ url_for('web.create_project') }}'"><span
                        class="am-icon-plus"></span> 新增
                </button>
            </div>

            <ul class="am-pagination am-fr">
                {% if paginate.has_prev %}
                    <a href="{{ url_for('web.list_projects', page=paginate.prev_num) }}">&lt;上一页</a>
                {% else %}
                    &lt;上一页
                {% endif %}

                {{ paginate.page }}

                {% if paginate.has_next %}
                    <a href="{{ url_for('web.list_projects', page=paginate.next_num) }}">下一页&gt;</a>
                {% else %}
                    下一页&gt;
                {% endif %}
            </ul>

            <hr/>
        </form>
    </div>
    <script type="text/javascript">

        {#function run_test_batch(type) {#}
        {#    let csrf = '{{ csrf_token() }}';#}
        {#    run_test_batch_common(type, csrf);#}
        {#}#}
        // 删除项目的 modal
        function invalid(id) {
            {#var csrf_token = "{{ csrf_token() }}";#}
            {#$.ajaxSetup({#}
            {#    beforeSend: function(xhr, settings) {#}
            {#        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {#}
            {#            xhr.setRequestHeader("X-CSRFToken", csrf_token);#}
            {#        }#}
            {#    }#}
            {#});#}

            $('#my-invalid').modal({
                relatedTarget: this,
                onConfirm : function () {
                    del_data_ajax(id, '{{ url_for("web.delete_project") }}')
                },
                onCancel : function() {

                }

            })
        };


        $('#mode').change(function () {
            if ($('#mode').val() === 'false') {
                $('#report_name').removeAttr("readonly");
            } else {
                $('#report_name').attr('readonly', 'readonly');
            }
        });

        {#function run_test(mode, url, type) {#}
        {#    if (mode === 'batch') {#}
        {#        if ($("input:checked").size() === 0) {#}
        {#            myAlert("请至少选择一个项目运行！");#}
        {#            return;#}
        {#        }#}
        {#        mode = JSON.stringify($("#project_list").serializeJSON());#}
        {#    }#}
        {#    $('#select_env').modal({#}
        {#        relatedTarget: this,#}
        {#        onConfirm: function () {#}
        {#            var data = {#}
                        {#"id": JSON.stringify($("#project_list").serializeJSON()),#}
        {#                "id": mode,#}
        {#                "env_name": $('#env_name').val(),#}
        {#                "type": type,#}
        {#                'report_name': $('#report_name').val(),#}
                        {#'csrf_token': "{{ csrf_token() }}"#}
        {#            };#}
        {#            post('/api/run_test/', data);#}
        {#        },#}
        {#        onCancel: function () {#}
        {#        }#}
        {#    });#}
        {#}#}

        $('#select_all').click(function () {
            var isChecked = $(this).prop("checked");
            $("input[name^='project']").prop("checked", isChecked);
        })
    </script>

{% endblock %}